spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    driver-class-name: org.h2.Driver
#    url: jdbc:p6spy:h2:tcp://localhost:9092/~/test
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password: sa
  sql:
    init:
      mode: always
