
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
  security:
    user:
      name: user
      password: user
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org:
      hibernate:
        SQL: debug

