spring:
  #  r2dbc:
  #    url: r2dbc:postgresql://localhost:5432/postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: secret
  security:
    user:
      name: user
      password: user
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        onLikeEvent-in-0:
            destination: likes
            group: web

logging:
  pattern.console: "%d{HH:mm:ss.SSS} [%12.12t] %clr(${LOG_LEVEL_PATTERN:%5p}) %.20logger{20} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
