spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: user
      password: user
  sql:
    init:
      mode: always
